### ISSUE TITLE
Feature request: Custom descriptions for different permissions?

### ISSUE THREAD

**Issue by NTT1906** [sky-min/CommandLib#9]

**Comment by sky-min** [comment]
Can you explain it in detail?

**Comment by NTT1906** [comment]
> Can you explain it in detail?
I'm still trying to figure out how it would work :l and I'm starting to wonder if it's pointless?

**Comment by NTT1906** [comment]
A thought occurred to me that if a normal player does not have that specific permission (Admin permission), it should provide other descriptions for more accurate information. But it's kind of pointless because PMMP no longer have child permissions...
